base:
  project_name: Social Distance Violation
  # set PYTHONPATH=%PYTHONPATH%;C:\project\ObjectDetection
input_config:
  image_location: data/images/image.jpg
  video_location: data/video/test.mp4

yolo_config:
  model_directory: data/dnn
  config_file: yolov3.cfg
  weights_file: yolov3.weights
  labels_file: coco.names

configuration_variables:
  use_gpu: false
  minimum_confidence_score: 0.3
  nms_threshold_value: 0.3
  minimum_distance: 150

artifacts:
  each_layer_output: artifacts/each_layer_output/each_layer_output.txt
  output_frame: artifacts/detections/image/output_frame.jpg