base:
  project_name: Social Distance Violation

input_config:
  image_location: inputs/image.jpg
  video_location: inputs/pedestrians.mp4

yolo_config:
  model_directory: tained_model
  config_file: yolov3.cfg
  weights_file: yolov3.weights
  labels_file: coco.names

configuration_variables:
  use_gpu: false
  minimum_confidence_score: 0.3
  nms_threshold_value: 0.3
  minimum_distance: 50

artifacts:
  each_layer_output: artifacts/each_layer_output.txt
  output_frame: artifacts/output_frame.jpg